### ISSUE TITLE
Improve Hydra seeding

### ISSUE THREAD

**Issue by uhbif19** [mlabs-haskell/hydra-auction#380]
**TODO:**

- [ ] Remove "fuel" marks (they are not used by Hydra node anymore)
- [ ] Add CLI action for seeding (now it is hardcoded in `.sh` scripts)
- [ ] Do seeding transactions in parallel (current sequential execution is very slow on public testnet)
- [ ] Do not seed if Hydra actors already have enough ADA
