### ISSUE TITLE
Improve cluster bootstrapping scripts

### ISSUE THREAD

**Issue by uhbif19** [mlabs-haskell/hydra-auction#382]
These scripts have multiple problems complicating their usage in non-main use-cases and reuse in non-hydra-auction projects (like https://github.com/eLearningDAO/POCRE/).

Also  `.sh` used for: envs, docker-compose deps control of cluster start, complex CLI actions, this makes stuff more fragile and less reusable.

Related: #380 , 

**TODO:**

- [ ] Hardcoded version of Hydra in docker-compose/sh scripts
- [ ] Docker-compose cannot be reused by non-hydra-auction projects
- [ ] Not checking that cluster it started correctly
